# vim:fileencoding=utf-8:foldmethod=marker
#

# Action Aliases
action_alias launch_tab launch --type=tab --cwd=current
action_alias hints kitten hints --hints-offset=0

# kitty_mod
kitty_mod ctrl+shift

map cmd+, edit_config_file

# Set dynamic mark
map kitty_mod+f1 create_marker
map kitty_mod+f2 remove_marker


# Scrollback 
map kitty_mod+down			scroll_line_down
map kitty_mod+up			scroll_line_up
map kitty_mod+page_up		scroll_page_up
map cmd+page_up				scroll_page_up
map kitty_mod+page_down		scroll_page_down
map cmd+page_down			scroll_page_down

#: Windows 
map cmd+n				new_os_window
map kitty_mod+enter		new_window

# map ctrl+j kitten pass_keys.py neighboring_window bottom ctrl+j
# map ctrl+k kitten pass_keys.py neighboring_window top    ctrl+k
# map ctrl+h kitten pass_keys.py neighboring_window left   ctrl+h
# map ctrl+l kitten pass_keys.py neighboring_window right  ctrl+l

map kitty_mod+p		nth_window -1

map kitty_mod+q		close_tab
map shift+cmd+i     set_tab_title
map kitty_mod+r		start_resizing_window

map alt+1 		first_window
map alt+2 		second_window
map alt+3 		third_window
map alt+4 		fourth_window
map alt+5 		fifth_window
map alt+6 		sixth_window
map alt+7 		seventh_window
map alt+8 		eighth_window
map alt+9 		ninth_window
map alt+0		tenth_window


# Tabs 
map cmd+]	next_tab
map cmd+[	previous_tab


map cmd+1	goto_tab 1
map cmd+2	goto_tab 2
map cmd+3	goto_tab 3
map cmd+4   goto_tab 4
map cmd+5	goto_tab 5
map cmd+6	goto_tab 6
map cmd+7	goto_tab 7
map cmd+8	goto_tab 8
map cmd+9	goto_tab 9
map cmd+0	goto_tab 10

# Font sizes 
map kitty_mod+backspace		change_font_size all 0
map kitty_mod+plus			change_font_size all +2.0
map kitty_mod+minus			change_font_size all -2.0

# Open URL
map kitty_mod+e				open_url_with_hints
map kitty_mod+p>shift+f 	kitten hints --type path

# Miscellaneous 
map cmd+,					edit_config_file
map kitty_mod+a>m			set_background_opacity +0.1
map kitty_mod+a>l 			set_background_opacity -0.1
map kitty_mod+a>1 			set_background_opacity 1
map ctrl+cmd+,				load_config_file


