# vim: set foldmethod=marker foldmarker={{{,}}}
# ~/.config/kitty/kitty.conf
# 

#: Environment  {{{
env VISUAL=nvim
env EDITOR=nvim
env IS_KITTY=1
# }}}

#: Fonts {{{
font_family				OperatorMono Nerd Font Medium
bold_font        		auto
italic_font      		auto
bold_italic_font 		auto
font_size				15
# }}}

#: Layouts {{{
remember_window_size	yes
initial_window_width  	1200
initial_window_height 	1000
enabled_layouts			fat:tall
window_padding_width	1 1 1 1
# }}}

#: Mouse {{{
mouse_hide_wait			3.0
copy_on_select			yes
# }}}

#: Shell {{{

term xterm-256color
shell_integration disabled
allow_remote_control	yes
shell					/bin/zsh
editor					/usr/local/bin/nvim
scrollback_lines		5000
enable_audio_bell		no
close_on_child_death	no:q
term					xterm-kitty
allow_hyperlinks		yes
# }}}

#: Tab Bar {{{
tab_title_template		"⌘{index} {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.default}{title}"
tab_fade				0.25 0.5 0.75 1
tab_switch_strategy		previous
tab_bar_edge			top
tab_bar_align			left
tab_bar_min_tabs		1
tab_bar_style			powerline
tab_powerline_style 	angled
tab_bar_margin_width	1.5
tab_bar_margin_height	1.5	1.5
# }}}

#: MacOS {{{
macos_titlebar_color				system
macos_option_as_alt					both
macos_thicken_font					0.5
macos_custom_beam_cursor			yes
macos_show_window_title_in			all
macos_hide_from_tasks				no
macos_quit_when_last_window_closed	no
macos_traditional_fullscreen		no
macos_custom_beam_cursor			yes

#action_alias launch_tab launch --type=tab --cwd=current
action_alias hints kitten hints --hints-offset=0
# }}}

#: Keybindings {{{ 

# kitty_mod
kitty_mod ctrl+shift

map cmd+, edit_config_file

# Set dynamic mark
map kitty_mod+f1 create_marker
map kitty_mod+f2 remove_marker


# Scrollback 
map kitty_mod+down			scroll_line_down
map kitty_mod+up			scroll_line_up
map kitty_mod+page_up		scroll_page_up
map cmd+page_up				scroll_page_up
map kitty_mod+page_down		scroll_page_down
map cmd+page_down			scroll_page_down

map kitty_mod+q		close_tab
map shift+cmd+i     set_tab_title
map kitty_mod+r		start_resizing_window

# Tabs 
map cmd+]	next_tab
map cmd+[	previous_tab
map cmd+1	goto_tab 1
map cmd+2	goto_tab 2
map cmd+3	goto_tab 3
map cmd+4   goto_tab 4
map cmd+5	goto_tab 5
map cmd+6	goto_tab 6
map cmd+7	goto_tab 7
map cmd+8	goto_tab 8
map cmd+9	goto_tab 9
map cmd+0	goto_tab 10

# Font sizes 
map kitty_mod+backspace		change_font_size all 0
map kitty_mod+plus			change_font_size all +2.0
map kitty_mod+minus			change_font_size all -2.0

# Open URL
map kitty_mod+e				open_url_with_hints
map kitty_mod+p>shift+f 	kitten hints --type path

# Miscellaneous 
map cmd+,					edit_config_file
map kitty_mod+a>m			set_background_opacity +0.1
map kitty_mod+a>l 			set_background_opacity -0.1
map kitty_mod+a>1 			set_background_opacity 1
map ctrl+cmd+,				load_config_file

# }}}

#: Included Files {{{ 
include themes/nightfox/duskfox/nightfox_kitty.conf

# }}}
