## vim: ft=yaml.ansible
---
- name: Setup OSX Development Workstation
  hosts: localhost

  tasks:

    - name: Add custom homebrew repos
      community.general.homebrew_tap:
        name: [
          epk/epk,
          homebrew/cask-versions,
        ]

    - name: Install core packages via brew casks
      community.general.homebrew_cask:
        name: "{{ item }}"
      with_items:
        - 1password
        - iterm2
        - font-sf-mono-nerd-font
        - ngrok
        - slack
        - github
        - wezterm-nightly
        - zoom

    - name: Install homebrew packages
      community.general.homebrew:
        name: [
          'autoconf',
          'automake',
          'aws-iam-authenticator',
          'awscli',
          'coreutils',
          'curl',
          'direnv',
          'fzf',
          'gpg',
          'htop',
          'kubectx',
          'kubernetes-cli',
          'kubernetes-helm',
          'libtool',
          'libxslt',
          'libyaml',
          'mas',
          'openssl',
          'pkg-config',
          'rcm',
          'readline',
          'tmux',
          'unixodbc',
          'unzip',
          'watchman',
          'xz',
          'yadm',
          'yarn',
          'zlib',
          'zsh',
        ]
        state: present
        update_homebrew: true

    - name: Install cargo packages
      community.general.cargo:
        name: "{{ item }}"
      with_items:
        - exa
        - rg
        - zoxide
        - stylua
        - bat
        -	broot 
	distant
