#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
trap 'rm -f "$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$$.tags" --languages=+Lua,JSON,Go,Markdown,Javascript,SQL,Python,Rust,Yaml,Typescript,AnsiblePlaybook
mv "$$.tags" "tags"
