#!/usr/bin/env zsh

if ! command -v pipx >/dev/null; then
    brew install pipx
fi

pkgs=(docker-squash ansible ansible-lint ansible-navigator httpie pyfunky pygments tmuxp)

for p in $pkgs; do
    pipx install $p
done
