#!/usr/bin/env zsh

# Install homebrew 
if ! command -v >/dev/null; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install dev workstation packages
brew install \
	asdf \
	autoconf \
	automake \
	autossh \
	byacc \
	bzip2 \
	coreutils \
	diff-so-fancy
	gawk \
	gcc \
	gh \
	gnu-sed \
	gnupg \
	howdoi \
	libevent \
	macvim \
	make \
    neovim \
    nodejs \
	pipx \
	pkg-config \
	pyenv \
	pyenv-virtualenv \
	pyenv-virtualenvwrapper \
	ranger \
	tldr \
	tmux \
	yamllint \
	zsh 


brew install --HEAD universal-ctags/universal-ctags/universal-ctags

brew tap homebrew/cask-fonts
brew install --cask font-sauce-code-pro-nerd-font
brew install --cask font-fira-code-nerd-font

brew install --HEAD neovim
