#!/usr/bin/env zsh

if ! command -v cargo >/dev/null; then
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
fi
source ~/.cargo/env

pkgs=(zoxide mcfly ripgrep fd-find broot bat exa)

for p in $pkgs; do
    cargo install $p
done


